//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson09_VAD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VadK22CNT2Lesson09DbEntities : DbContext
    {
        public VadK22CNT2Lesson09DbEntities()
            : base("name=VadK22CNT2Lesson09DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vadKhoa> vadKhoas { get; set; }
        public virtual DbSet<vadSinhVien> vadSinhViens { get; set; }
    }
}
