//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson09_VAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadSinhVien
    {
        public string VadMaSV { get; set; }
        public string VadHoSV { get; set; }
        public string VadTenSV { get; set; }
        public Nullable<System.DateTime> VadNgaySinh { get; set; }
        public Nullable<bool> VadPhai { get; set; }
        public string VadPhone { get; set; }
        public string VadEmail { get; set; }
        public string VadMaKH { get; set; }
    
        public virtual vadKhoa vadKhoa { get; set; }
    }
}
