//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson10_VAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadKetQua
    {
        public string vadMaSV { get; set; }
        public string vadMaMH { get; set; }
        public Nullable<int> vadDiem { get; set; }
    
        public virtual vadMonHoc vadMonHoc { get; set; }
        public virtual vadSinhVien vadSinhVien { get; set; }
    }
}
