//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson10_VAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadMonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vadMonHoc()
        {
            this.vadKetQuas = new HashSet<vadKetQua>();
        }
    
        public string vadMaMH { get; set; }
        public string vadTenMH { get; set; }
        public Nullable<int> vadSotiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vadKetQua> vadKetQuas { get; set; }
    }
}
