//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson10_VAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vadSinhVien()
        {
            this.vadKetQuas = new HashSet<vadKetQua>();
        }
    
        public string vadMaSV { get; set; }
        public string vadHoSV { get; set; }
        public string vadTenSV { get; set; }
        public Nullable<bool> vadPhai { get; set; }
        public Nullable<System.DateTime> vadNgaySinh { get; set; }
        public string vadNoiSinh { get; set; }
        public string vadMaKH { get; set; }
        public string vadHocBong { get; set; }
        public Nullable<int> vadDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vadKetQua> vadKetQuas { get; set; }
        public virtual vadKhoa vadKhoa { get; set; }
    }
}
