//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson09_VAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vadKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vadKhoa()
        {
            this.vadSinhViens = new HashSet<vadSinhVien>();
        }
    
        public string VadMaKH { get; set; }
        public string VadTenKH { get; set; }
        public Nullable<bool> VadTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vadSinhVien> vadSinhViens { get; set; }
    }
}
